
# Define a versão da especificação do Docker Compose.
version: "3.3"

# Define os serviços disponíveis no ambiente Docker.
services:
  # Configuração do serviço Redis.
  redis:
    # Usa a imagem Redis versão 6.0.7 do Docker Hub.
    image: redis:6.0.7
    # Define o nome do contêiner como "redis".
    container_name: redis
    # Configura o contêiner para reiniciar automaticamente em caso de falha.
    restart: always
    # Cria um volume chamado "redis_volume_data" e o monta no diretório "/data" dentro do contêiner.
    volumes:
      - redis_volume_data:/data
    # Mapeia a porta 6379 do host para a porta 6379 do contêiner.
    ports:
      - 6379:6379

  # Configuração do serviço Redis Insight.
  redis_insight:
    # Usa a imagem mais recente do RedisInsight do Docker Hub.
    image: redislabs/redisinsight:latest
    # Define o nome do contêiner como "redis_insight".
    container_name: redis_insight
    # Configura o contêiner para reiniciar automaticamente em caso de falha.
    restart: always
    # Mapeia a porta 8001 do host para a porta 8001 do contêiner.
    ports:
      - 8001:8001
    # Cria um volume chamado "redis_insight_volume_data" e o monta no diretório "/db" dentro do contêiner.
    volumes:
      - redis_insight_volume_data:/db

# Define os volumes a serem utilizados pelos serviços.
volumes:
  # Define o volume "redis_volume_data".
  redis_volume_data:
  # Define o volume "redis_insight_volume_data".
  redis_insight_volume_data:


